[package]
name = "voting-program"
version = "0.1.0"
description = "Solana voting program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init", "derive"] }
anchor-spl = "0.29.0"
